app1/urls.py
from django.urls import path
from app1.views import *
app_name='something'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='nothing'
urlpatterns=[
    path('virat/',virat,name='virat'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render
def dhoni(request):
    return render(request,'dhoni.html')

# Create your views here.

app2/views.py
from django.shortcuts import render
def virat(request):
    return render(request,'virat.html')

# Create your views here.

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is dhoni html page</h1>
        <h1>This page belongs to app1 and it is specific url</h1>
        <a href="{% url 'nothing:virat' %}">to navigate from dhoni page to virat page</a>
    </center>
    
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This page belongs to virat</h1>
        <h1>this page belongs to app2 </h1>
        <a href="{% url 'something:dhoni' %}">to navigate from virat page to dhoni page</a>
    </center>
    
</body>
</html>